name: Check Changes Since Last Release
description: Checks if there were changes in the provided directory since the last release
inputs:
  directory:
    description: The directory to check for changes
    required: true
  commitMessage: # New input for commit message
    description: 'The message of the commit'
    required: true
runs:
  using: composite
  steps:
    - id: check-changes
      run: |
        echo "Checking changes in ${{ inputs.directory }}"

        LATEST_TAG=$(git tag --sort=-creatordate | head -n 1 2>/dev/null || echo "")
        PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2{p;q}' 2>/dev/null || echo "")

        CURRENT_COMMIT_MSG="${{ inputs.commitMessage }}"
        echo "Current commit message: $CURRENT_COMMIT_MSG"

        if [[ ! $CURRENT_COMMIT_MSG =~ ^chore.*release ]]; then
          echo "This commit is not a release. Skipping."
          echo "changed=false" >> $GITHUB_OUTPUT
        elif [[ -z "$LATEST_TAG" ]]; then
          echo "No tags found. Assuming no changes."
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          # Check if directory exists at the latest and previous tags
          DIRECTORY_EXISTS_AT_LATEST=$(git ls-tree -d $LATEST_TAG -- ${{ inputs.directory }} | wc -l)
          DIRECTORY_EXISTS_AT_PREVIOUS=$(git ls-tree -d $PREVIOUS_TAG -- ${{ inputs.directory }} | wc -l)

          # If directory does not exist at the latest tag but existed at the previous tag, assume changes
          if [[ "$DIRECTORY_EXISTS_AT_LATEST" == "0" && "$DIRECTORY_EXISTS_AT_PREVIOUS" != "0" ]]; then
            echo "Directory existed at the previous tag but does not exist at the latest tag. Assuming changes."
            echo "changed=true" >> $GITHUB_OUTPUT
          # If directory does not exist at the latest tag and did not exist at the previous tag, assume no changes
          elif [[ "$DIRECTORY_EXISTS_AT_LATEST" == "0" && "$DIRECTORY_EXISTS_AT_PREVIOUS" == "0" ]]; then
            echo "Directory does not exist at the latest tag or the previous tag. Assuming no changes."
            echo "changed=false" >> $GITHUB_OUTPUT
          # If directory exists at the latest tag, check for changes
          elif [[ "$DIRECTORY_EXISTS_AT_LATEST" != "0" ]]; then
            if [[ -z "$PREVIOUS_TAG" ]]; then
              echo "Only one tag found. Assuming changes."
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              if git diff --quiet $PREVIOUS_TAG..$LATEST_TAG -- ${{ inputs.directory }} &>/dev/null; then
                echo "No changes in ${{ inputs.directory }} between last two releases."
                echo "changed=false" >> $GITHUB_OUTPUT
              else
                echo "Changes detected in ${{ inputs.directory }} between last two releases."
                echo "changed=true" >> $GITHUB_OUTPUT
              fi
            fi
          fi
        fi
      shell: bash
