name: Check Changes Since Last Release
description: Checks if there were changes in the provided directory since the last release
inputs:
  directory:
    description: The directory to check for changes
    required: true
  commitMessage: # New input for commit message
    description: 'The message of the commit'
    required: true
outputs:
  changed:
    description: True if the directory has changed since the last release, false otherwise
    value: ${{ steps.check-changes.outputs.changed }}
runs:
  using: composite
  steps:
    - id: check-changes
      run: >
        echo "Checking changes in ${{ inputs.directory }}"

        LATEST_RELEASE_HASH=$(git rev-list --tags --max-count=1 2>/dev/null || echo "")

        SECOND_LATEST_RELEASE_HASH=$(git rev-list --tags --skip=1 --max-count=1 2>/dev/null || echo "")

        CURRENT_COMMIT_MSG="${{ inputs.commitMessage }}"
        
        echo "Current commit message: $CURRENT_COMMIT_MSG"

        if [[ ! $CURRENT_COMMIT_MSG =~ ^chore.*release ]]; then
          echo "This commit is not a release. Skipping."
          echo "changed=false" >> $GITHUB_ENV
        elif [[ -z "$LATEST_RELEASE_HASH" || -z "$SECOND_LATEST_RELEASE_HASH" ]]; then
          echo "Less than two releases found. Assuming changes."
          echo "changed=true" >> $GITHUB_ENV
        else
          git diff --quiet $SECOND_LATEST_RELEASE_HASH..$LATEST_RELEASE_HASH -- ${{ inputs.directory }} || true
          CHANGES=$?
          if [[ "$CHANGES" == "0" ]]; then
            echo "No changes in ${{ inputs.directory }} between last two releases. Skipping."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected in ${{ inputs.directory }} between last two releases."
            echo "changed=true" >> $GITHUB_ENV
          fi
        fi
      shell: bash
